# Cleaning Data

In [2]:
import pandas as pd
import numpy as np
import missingno as mno
import seaborn as sns

In [10]:
# loading data
df_diabetes = pd.read_csv("/Users/saidalkildani/Desktop/DS_AI/Projects/ML_diabetes_SA/ml-diabetes-SA/ML_diabetes.csv")

In [11]:
df_diabetes

,id,Age,pregnancies,bmi,insulin,glucose,bloodpressure,patientid,measurement_date,skinthickness,diabetespedigreefunction,outcome
0,1,50,6,33.6,0,148,72,1,2022-12-13,35,0.627,1
1,2,31,1,26.6,0,85,66,2,2022-12-13,29,0.351,0
2,3,32,8,23.3,0,183,64,3,2022-12-13,0,0.672,1
3,4,21,1,28.1,94,89,66,4,2022-12-13,23,0.167,0
4,5,33,0,43.1,168,137,40,5,2022-12-13,35,2.288,1
...,...,...,...,...,...,...,...,...,...,...,...,...
763,764,63,10,32.9,180,101,76,764,2022-12-13,48,0.171,0
764,765,27,2,36.8,0,122,70,765,2022-12-13,27,0.340,0
765,766,30,5,26.2,112,121,72,766,2022-12-13,23,0.245,0
766,767,47,1,30.1,0,126,60,767,2022-12-13,0,0.349,1
767,768,23,1,30.4,0,93,70,768,2022-12-13,31,0.315,0

## Columns and Data Types

In [ ]:
# Check data types
df_diabetes.dtypes
## no need for conversions

id                            int64
Age                           int64
pregnancies                   int64
bmi                         float64
insulin                       int64
glucose                       int64
bloodpressure                 int64
patientid                     int64
measurement_date             object
skinthickness                 int64
diabetespedigreefunction    float64
outcome                       int64
dtype: object

In [ ]:
## Drop unnecessary columns
df_diabetes.drop(columns=['patientid'], inplace=True)
df_diabetes.drop(columns=['measurement_date'], inplace=True)

## Missing values

In [ ]:
# Check for missing values
df_diabetes.isnull().sum()
## no missing values

id                          0
Age                         0
pregnancies                 0
bmi                         0
insulin                     0
glucose                     0
bloodpressure               0
skinthickness               0
diabetespedigreefunction    0
outcome                     0
dtype: int64

In [ ]:
# Check for zero values in features
df_diabetes.describe()
# Zero values in insulin, skin thickness, glucose, bmi, and blood pressure are not acceptable measurements. 
# Replace the zeros with mean values after train-test splitting the data

,id,Age,pregnancies,bmi,insulin,glucose,bloodpressure,patientid,skinthickness,diabetespedigreefunction,outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,384.500000,33.240885,3.845052,32.450805,118.660163,121.681605,72.254807,384.500000,26.606479,0.471876,0.348958
std,221.846794,11.760232,3.369578,6.875374,93.080358,30.436016,12.115932,221.846794,9.631241,0.331329,0.476951
min,1.000000,21.000000,0.000000,18.200000,14.000000,44.000000,24.000000,1.000000,7.000000,0.078000,0.000000
25%,192.750000,24.000000,1.000000,27.500000,79.799479,99.750000,64.000000,192.750000,20.536458,0.243750,0.000000
50%,384.500000,29.000000,3.000000,32.000000,79.799479,117.000000,72.000000,384.500000,23.000000,0.372500,0.000000
75%,576.250000,41.000000,6.000000,36.600000,127.250000,140.250000,80.000000,576.250000,32.000000,0.626250,1.000000
max,768.000000,81.000000,17.000000,67.100000,846.000000,199.000000,122.000000,768.000000,99.000000,2.420000,1.000000

## Checking for Duplicates

In [14]:
# There are no duplicates in the data
df_diabetes[df_diabetes.duplicated()]

Empty DataFrame
Columns: [id, Age, pregnancies, bmi, insulin, glucose, bloodpressure, skinthickness, diabetespedigreefunction, outcome]
Index: []

## Saving the Clean Data

In [15]:
# Export the clean data to a csv-file
df_diabetes.to_csv('ML_diabetes_clean.csv',index=False)